import oracledb

def get_connection():
    return oracledb.connect(
        user="samir1",
        password='12345',
        dsn="localhost/orcl"
    )

def create_tables():
    conn=get_connection()
    cursor=conn.cursor()

    cursor.execute(
        """
    BEGIN 
         EXECUTE IMMEDIATE 'CREATE TABLE departaments(
                id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                name VARCHAR2(100),
                location VARCHAR2(100),
                PRIMARY KEY(id)
                )';
    EXCEPTION
            WHEN OTHERS THEN
                    IF SQLCODE=-955 THEN
                        RAISE;
                    END IF;
    END;                                
"""
    )

    cursor.execute(
        """
    BEGIN
        EXECUTE IMMEDIATE 'CREATE TABLE employees(
        id NUMBER GENERATED BY DEFAULT AS IDENTITY,
        username VARCHAR2(50),
        salary NUMBER(10,2),
        department_id NUMBER,
        PRIMARY KEY(id)
        )';
    EXCEPTION
            WHEN OTHERS THEN
                    IF SQLCODE=-955 THEN
                        RAISE;
                    END IF;
    END;     
"""
    )

    conn.commit()
    cursor.close()
    conn.close()