import oracledb

def get_connection(): 
    return oracledb.connect(
        user="samir1",
        password="12345",
        dsn="localhost/orcl" # SYS istifadəçisi üçün bu vacibdir
    )
    
def create_tables():
    conn = None
    try:
        conn = get_connection()
        cursor = conn.cursor()

        # Authors cədvəli
        cursor.execute("""
        BEGIN 
           EXECUTE IMMEDIATE 'CREATE TABLE authors (
               author_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
               name VARCHAR2(50) UNIQUE,
               PRIMARY KEY (author_id)
           )';
        EXCEPTION
           WHEN OTHERS THEN
              IF SQLCODE != -955 THEN
                 RAISE;
              END IF;
        END;
        """)
       
        # Books cədvəli
        cursor.execute("""
        BEGIN
            EXECUTE IMMEDIATE 'CREATE TABLE books(
                book_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                title VARCHAR2(100),
                price NUMBER,
                author_id NUMBER,
                CONSTRAINT pk_books PRIMARY KEY (book_id),
                CONSTRAINT fk_author 
                    FOREIGN KEY (author_id) 
                    REFERENCES authors(author_id)
            )';
        EXCEPTION
            WHEN OTHERS THEN
                IF SQLCODE != -955 THEN
                    RAISE;
                END IF;
        END;
        """)
       
        conn.commit()
        print("Cədvəllər uğurla yaradıldı (və ya artıq mövcuddur).")
    except oracledb.Error as e:
        print(f"Xəta baş verdi: {e}")
    finally:
        if conn:
            cursor.close()
            conn.close()

